os: linux
dist: xenial
language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  CI_TEST_SERVER: 1

before_install:
  ## php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  ## cp script required for test
  - cp test_server/request.php request.php
  ## composer
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist
  - sudo nohup php -S 0.0.0.0:80 -t test_server > /dev/null 2>&1 &

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

cache:
  directories:
    - $HOME/.composer/cache